// ===----------------------------------------------------------------------===//
//
// SPDX-FileCopyrightText: (c) 2024 SpacemiT
// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef XSMTASYNC
#define XSMTASYNC

include "triton-shared/Dialect/XSMTAsync/IR/XSMTAsyncDialect.td"
include "triton-shared/Dialect/XSMTAsync/IR/XSMTAsyncOps.td"

#endif // XSMTASYNC